### ISSUE TITLE
Image-based data transport?

### ISSUE THREAD

**Issue by developit** [wooorm/server-components-mdx-demo#2]
Hiya! This is neato. However, I was confused about the justification given for the image-based data serialization. While it's true `<script type=text>` can't contain the literal text content `</script>`, it can contain `<\/script>`:

```html
<script id="a" type="text">{"foo":"Hello <\/script>"}</script>

<script>
    console.log(JSON.parse(a.textContent));
</script>
```

Serialized JSON conveniently handles this by default. For prod it's better to use something like [devalue](https://github.com/Rich-Harris/devalue), which prevents a few additional nefarious injection vectors like lone surrogates, and supports things like Maps and Sets.

**Comment by wooorm** [comment]
"React" is giving me this, what seems to be, newline delimited json. I felt it best to not try and decode/encode that format because maybe it'll change? 🤷‍♂️ This whole thing is also something they're aware of and will fix from what I heard!

**Comment by wooorm** [comment]
For `</script>`, I oversimplified with saying “characters”, because there can also be whitespace after `script`, or even `</script/>`, or attributes on it, `</script whatever>`
— https://html.spec.whatwg.org/multipage/parsing.html#script-data-state

**Comment by wooorm** [comment]
Ok closing this as a 🤷‍♂️ I don’t really care about Brave doing weird things. If there’s a better way to stream arbitrary (binary?) data to browsers, I’d love to hear it though! Maybe browsers should have a `<buffer>` element!
